Repository KongSwap/kong, pull requests merged in 2024-12, with the labels that each got.

#205 Feat/kong/v/2.5
  src/kong_svelte/src/lib/components/liquidity/add_liquidity/AddLiquidityConfirmation.svelte
  src/kong_svelte/src/lib/components/liquidity/add_liquidity/AddLiquidityForm.svelte
  src/kong_svelte/src/lib/components/liquidity/pools/PoolRow.svelte
  src/kong_svelte/src/lib/components/liquidity/pools/UserPool.svelte
  src/kong_svelte/src/lib/components/sidebar/PoolList.svelte
  src/kong_svelte/src/lib/components/sidebar/SendTokens.svelte
  src/kong_svelte/src/lib/components/sidebar/TransactionHistory.svelte
  src/kong_svelte/src/lib/components/swap/Swap.svelte
  src/kong_svelte/src/lib/services/db.ts
  src/kong_svelte/src/lib/services/icrc/IcrcService.ts
  src/kong_svelte/src/lib/services/pnp/PnpInitializer.ts
  src/kong_svelte/src/lib/services/tokens/TokenService.ts
  src/kong_svelte/src/lib/services/tokens/tokenStore.ts
  src/kong_svelte/src/lib/utils/numberFormatUtils.ts
  src/kong_svelte/src/lib/utils/tokenFormatters.ts
  src/kong_svelte/src/routes/earn/+page.svelte
  src/kong_svelte/src/routes/stats/+page.svelte
Labels: FE, BE

#227 ii mobile fix
  src/kong_svelte/package.json
  src/kong_svelte/src/lib/services/auth.ts
  src/kong_svelte/src/lib/services/pnp/PnpInitializer.ts
Labels: bug

#269 Add dialogs for plug mobile, add browser utils tests
  .github/pull_request_template.md
  src/kong_svelte/src/lib/components/common/AddToHomeScreen.svelte
  src/kong_svelte/src/lib/components/common/Dialog.svelte
  src/kong_svelte/src/lib/components/common/InstallPWADialog.svelte
  src/kong_svelte/src/lib/components/earn/UserPoolList.svelte
  src/kong_svelte/src/lib/components/liquidity/AddLiquidity.svelte
  src/kong_svelte/src/lib/components/liquidity/add_liquidity/AddLiquidityForm.svelte
  src/kong_svelte/src/lib/components/liquidity/add_liquidity/AddLiquidityModal.svelte
  src/kong_svelte/src/lib/components/liquidity/pools/UserPool.svelte
  src/kong_svelte/src/lib/components/sidebar/PoolList.svelte
  src/kong_svelte/src/lib/components/sidebar/TokenRow.svelte
  src/kong_svelte/src/lib/components/sidebar/WalletProvider.svelte
  src/kong_svelte/src/lib/components/swap/swap_ui/TokenSelectorDropdown.svelte
  src/kong_svelte/src/lib/components/wallet/PlugMobileDialog.svelte
  src/kong_svelte/src/lib/services/pools/PoolService.ts
  src/kong_svelte/src/lib/services/pools/addLiquidityStore.ts
  src/kong_svelte/src/lib/services/pools/poolStore.ts
  src/kong_svelte/src/lib/services/tokens/TokenService.ts
  src/kong_svelte/src/lib/services/tokens/favoriteStore.ts
  src/kong_svelte/src/lib/services/tokens/tokenStore.ts
  src/kong_svelte/src/lib/stores/modalStore.ts
  src/kong_svelte/src/lib/types/pwa.d.ts
  src/kong_svelte/src/lib/types/window.d.ts
  src/kong_svelte/src/lib/utils/browser.ts
  src/kong_svelte/src/lib/utils/liquidityUtils.ts
  src/kong_svelte/src/lib/utils/tokenFormatters.ts
  src/kong_svelte/static/apps/apple.svg
  src/kong_svelte/static/apps/google-play.svg
  src/kong_svelte/test/utils/browser.test.ts
Labels: enhancement, FE
